### ISSUE TITLE
 "fmt::fmt-header-only" but the target   was not found

### ISSUE THREAD

**Issue by trappedinspacetime** [contour-terminal/termbench-pro#7]
I am on Ubuntu 20.04 platform. 
I get the following errors:

           CMake Error at libtermbench/CMakeLists.txt:1 (add_library):
            Target "termbench" links to target "fmt::fmt-header-only" but the target
            was not found.  Perhaps a find_package() call is missing for an IMPORTED
            target, or an ALIAS target is missing?
          
          
          CMake Error at termbenchpro/CMakeLists.txt:1 (add_executable):
            Target "tbp" links to target "fmt::fmt-header-only" but the target was not
            found.  Perhaps a find_package() call is missing for an IMPORTED target, or
            an ALIAS target is missing?
          
          
          CMake Error at termbenchpro/CMakeLists.txt:1 (add_executable):
            Target "tbp" links to target "fmt::fmt-header-only" but the target was not
            found.  Perhaps a find_package() call is missing for an IMPORTED target, or
            an ALIAS target is missing?
          
          
          -- Generating done
          CMake Generate step failed.  Build files cannot be regenerated correctly.

**Comment by christianparpart** [comment]
Hey @trappedinspacetime.

Sorry for the obviously late response. We've finally moved forward on this end here and do not require fmtlib explicitly anymore, now, since we've moved to C++20, we're making use of `fmt::format` instead. :)
